#!/usr/bin/env bash
# transfers a file to a remote server
if (($# < 3))
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
scp -o StrictHostKeyChecking=no -o IdentityFile="$4" "$1" "$3"@"$2":~/