#!/usr/bin/env bash
# installs nginx on a server
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart