#!/usr/bin/env bash
# redirects a sepcific URL to another site
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '37i\rewrite ^/redirect_me http://google.com permanent;' /etc/nginx/sites-available/default
sudo service nginx restart