#!/usr/bin/env bash
# redirects a sepcific URL to another site
sudo apt install -y nginx
sudo service nginx start
new_string="server_name _;\n\trewrite ^\/redirect_me$ http:\/\/google.com permanent;"
sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-available/default
sudo service nginx restart