#!/usr/bin/env bash

function con_k {
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit 1
}
function con_c {
	echo "Y U no love me?!"
}
echo $$ > /var/run/myscript.pid
while :
do
	echo "To infinity and beyond"
	trap con_c SIGINT
	trap con_k SIGTERM
	trap con_k SIGQUIT
	sleep 2
done
