#!/usr/bin/env bash
# manages a process
start () {
    ./manage_my_process &
    sudo echo "$!" | sudo tee /var/run/my_process.pid > /dev/null
    echo "manage_my_process started"
}

stop () {
    kill "$(cat /var/run/my_process.pid)"
    sudo rm /var/run/my_process.pid
    echo "manage_my_process stopped"
}

restart () {
    kill "$(cat /var/run/my_process.pid)"
    sudo rm /var/run/my_process.pid
    ./manage_my_process &
    sudo echo "$!" | sudo tee /var/run/my_process.pid > /dev/null
    echo "manage_my_process restarted"
}
case "$1" in
   start) start ;;
   stop)  stop;;
   restart) restart;;
   *) echo "Usage: $0 {start|stop|restart}" >&2
      exit 1
      ;;
esac